language: node_js
node_js:
  - "lts/*"

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.38.2/hugo_0.38.2_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - hugo version
  - yarn --frozen-lockfile --silent --non-interactive --no-progress

script:
  - commitlint-travis
  - ./bin/lint_css.sh
  - ./bin/prod.sh

# non-sudo for a [faster](https://docs.travis-ci.com/user/reference/overview/#Container-based) container-based build.
sudo: false

git:
  submodules: false

notifications:
  email: false

cache:
  yarn: true
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  local-dir: public
  fqdn: dkannan.com
  target-branch: gh-pages
  on:
    branch: master