baseURL = "http://dkannan.com/"
title = "personal blog of Deepak Kannan"

theme = "everest"

languageCode = "en-us"
enableRobotsTXT = "true"
enableEmoji = "true"
enableGitInfo = "false"
disableHugoGeneratorInject = "true"

buildDrafts = "false"
buildExpired = "false"
buildFuture = "false"

disableKinds = ["RSS","sitemap","taxonomy","taxonomyTerm","page","section"]

[taxonomies]
  category = ""
  tags = ""