baseURL = "https://dkannan.com/"
title = "Deepak Kannan | Programmer"

languageCode = "en-us"
enableRobotsTXT = "true"
enableEmoji = "true"
enableGitInfo = "false"
disableHugoGeneratorInject = "true"

buildDrafts = "false"
buildExpired = "false"
buildFuture = "false"

disableKinds = ["RSS","sitemap","taxonomy","taxonomyTerm"]

[taxonomies]
  category = ""
  tags = ""